Стилистика локализации
TwoEightNine/XVII pull request #12
Opened 2022-01-10 07:12 UTC by butyoutried

Привет! Немного поправил текст.

Добавил поддержку "ё", которой местами не было.

Заменил "прикрепления" на привычные "вложения", "иконки" на более уместные "значки".

В статусе отношений, раз уж используются "помолвлен(а)" и "влюблен(а)", "один" лучше изменить тоже на что-то гендерно-нейтральное. Указал "без пары".

Ну и по мелочи поправил кальки с английского, канцеляризм и избыточные слова. Например, громоздкие существительные лучше заменять глаголами, текст становится живее ("необходимо подтверждение профиля" —> "необходимо подтвердить профиль"). Родительный падеж тоже не всегда смотрится хорошо ("совершение действия не разрешено" = "действие не разрешено").

"do you really..." и "really...", а также "вы действительно..." и "действительно..." чередуются. Причём иногда "do you really..." переведено как "действительно...". Добавил в недостающих местах "вы" и "do you".

Ну и если русские "свежие новости" — это устойчивая тавтология, то в английском сочетание "freshest news" используют редко, по смыслу больше подходит "latest news".

Спасибо за отличный клиент :)

2022-01-10 15:48 UTC, TwoEightNine requested changes
в целом согласен, есть замечание

2022-01-10 15:48 UTC, TwoEightNine commented on app/src/main/res/values-ru/strings.xml
> +    <string name="error_17">необходимо подтвердить профиля</string>
*профиль

2022-01-11 12:41 UTC, butyoutried commented on app/src/main/res/values-ru/strings.xml
> +    <string name="error_17">необходимо подтвердить профиля</string>
Точно, пропустил. Исправлено.

2022-01-11 13:40 UTC, TwoEightNine approved these changes

2022-01-11 13:41 UTC, merged

2022-01-11 13:42 UTC, TwoEightNine commented
спасибо за помощь в развитии проекта и добро пожаловать в список контрибьюторов!